### PR TITLE
include publish binary scripts

### PR DESCRIPTION
**Pull request by mapsam**
Working on #14 

This adds a bit more cruft, but seems pretty worthwhile if it allows others to actually `npm install` and use the library?

cc @springmeyer @mikemorris @GretaCB @jakepruitt

### CODE REVIEW

**Comment by mikemorris** [comment]
I rigged up [a script to only publish on git tags](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/node/scripts/after_script.sh) for mapbox-gl-native, but unfortunately it doesn't support Bitrise, as it relies on the [`TRAVIS_TAG`](https://github.com/mapbox/mapbox-gl-native/blob/master/.travis.yml#L68) environment variable. Figuring out some convention that works across Travis CI, Bitrise and Circle CI here would be great.

**Comment by springmeyer** [comment]
👍  Great stuff @mapsam.

Also, I think we should start refactoring all logic into a single bash file. Then the convention can be to source this single bash file for its functions and call them. So, what do you think about combining `scripts/is_pr_merge.sh` and `scripts/publish.sh` into a single `scripts/common.sh` that could be easily copied from this repo to other node c++ projects? My inspiration for this is https://github.com/mapnik/mapnik/blob/master/scripts/travis-common.sh

> Figuring out some convention that works across Travis CI, Bitrise and Circle CI here would be great.

👍

**Comment by mapsam** [comment]
Oooh @mikemorris I like the idea of building ONLY on tags a lot. I've included the [logic in `vtinfo` to NOT build on tags](https://github.com/mapbox/vtinfo/pull/4/files#diff-354f30a63fb0907d4ad57269548329e3R5). Could we do a combination of build on tags AND an option to republish binaries if necessary?

**Comment by mikemorris** [comment]
@mapsam Yea-ish. That's what how [the binary publishing script in node-fontnik](https://github.com/mapbox/node-fontnik/blob/master/scripts/travis_publish.sh#L16) is currently written, but the problem is that the equivalent `BITRISE_GIT_TAG` [doesn't work as expected](https://github.com/mapbox/mapbox-gl-native/issues/4854). Would be great to get this figured out and fixed!

**Comment by mapsam** [comment]
Merging this for now - going to open separate tickets about further consolidation and circleci/bitrise additions.

**Comment by springmeyer** [comment]
👍  @mapsam

**Pull request merged**
