### PR TITLE
Use Async Workers for Heavy Async. Tasks

### PR DESCRIPTION
**Pull request by daniel-j-h**
This repository is great for getting people up to speed with Node bindings and Nan.

Let's switch over to Nan's AsncWorkers for async. tasks.
It's simpler, clearer and less error prone then doing it ourselves with uv.

Somewhat related: #5.

cc @springmeyer

### CODE REVIEW

**Comment by daniel-j-h** [comment]
Fixed some remaining issues - Linux builds on Travis are green. Waiting for macOS builds (will take a while, will check tomorrow).

**Comment by springmeyer** [comment]
Thanks for working in this! I'll test on os x later today.

**Comment by daniel-j-h** [comment]
Ping - just came across this again by accident, while checking out this project for its node-pre-gyp integration. What's the status here @springmeyer - anything blocking?

**Comment by GretaCB** [comment]
hey @daniel-j-h 👋 , thanks for getting this PR going! I'm currently refactoring the skel, and going to integrate AsyncWorkers in a new branch coming soon, stay tuned

**Comment by daniel-j-h** [comment]
Great, thank you! 👍

**Comment by GretaCB** [comment]
Implemented over at https://github.com/mapbox/node-cpp-skel/pull/46

**Pull request closed without merging**
