### PR TITLE
add promise function

### PR DESCRIPTION
**Pull request by mapsam**
Adds a promise function `helloPromise` to expose the Napi::Promise methods. 

Lots of inspiration from https://github.com/nodejs/node-addon-examples/issues/85

cc @springmeyer @artemp

### CODE REVIEW

**Comment by mapsam** [comment]
Currently playing whack-a-mole with the clang TIDY options - here are two conflicting reports:

```
../src/standalone_promise/hello_promise.cpp:12:5: error: ‘standalone_promise::PromiseWorker::output’ should be initialized in the member initialization list [-Werror=effc++]
     PromiseWorker(Napi::Env const& env, std::string phrase, int multiply)
```

And if the change is made to add `output()` to the initializer list, the clang tidy build fails with:

```
/home/travis/build/mapbox/node-cpp-skel/build/../src/standalone_promise/hello_promise.cpp:17:11: error: initializer for member 'output' is redundant [readability-redundant-member-init,-warnings-as-errors]
          output() {}
```

**Comment by artemp** [comment]
> Currently playing whack-a-mole with the clang TIDY options - here are two conflicting reports:
> 
> ```
> ../src/standalone_promise/hello_promise.cpp:12:5: error: ‘standalone_promise::PromiseWorker::output’ should be initialized in the member initialization list [-Werror=effc++]
>      PromiseWorker(Napi::Env const& env, std::string phrase, int multiply)
> ```
> 
> And if the change is made to add `output()` to the initializer list, the clang tidy build fails with:
> 
> ```
> /home/travis/build/mapbox/node-cpp-skel/build/../src/standalone_promise/hello_promise.cpp:17:11: error: initializer for member 'output' is redundant [readability-redundant-member-init,-warnings-as-errors]
>           output() {}
> ```
Interestingly, I don't see this with `make tidy` (?)

**Review by artemp — CHANGES_REQUESTED** [review]
Couple nitpicking suggestions : 
* remove redundant old `node-pre-gyp` from packages.json
* require latest `node-addon-api` 4.3.0 or greater

**Comment by mapsam** [comment]
@artemp thanks for the review! Changes are in https://github.com/mapbox/node-cpp-skel/pull/169/commits/84c98487755da263f58be12092ad7dbf96dbb66f

**Review by artemp — COMMENTED** [review]
@mapsam :+1: great!  ~~Just wondering if changes in binding.gyp are intentional or? Is the intention here to avoid mason toolchain and use defaults from travis-ci?~~

**Review by artemp — APPROVED** [review]

**Comment by mapsam** [comment]
@artemp nope, accidentally committed those. Removed in https://github.com/mapbox/node-cpp-skel/pull/169/commits/19c4d4494ff446cbba4706e2b2a9ecdde270f951! 

I'm working over at https://github.com/mapbox/node-cpp-skel/tree/xcode-updates to try and update the xcode versions, which appear to have relocated the location of std on my machine between versions, hence the commented-out clang++ settings. I'm just using the system default c++ to build now, which appears to work just fine. If you have thoughts on how to remedy this in node-pre-gyp, I'm all ears!

**Pull request merged**
