### PR TITLE
Add npm publish as dev option

### PR DESCRIPTION
**Pull request by GretaCB**
Per chat with @allieoop , including npm dev publish option as part of our docs.

cc @mapsam @springmeyer

### CODE REVIEW

**Comment by GretaCB** [comment]
Uh, I have no idea why codecoverage failed with https://codecov.io/gh/mapbox/node-cpp-skel/compare/7ea33af8bc73a7e0fe4a0e3e466fca839ddbb095...ed14a770b6091057eea6ca60eb07166cc2cb00a5/changes o_O

**Comment by millzpaugh** [comment]
@GretaCB realizing that I created a PR to update docs with these changes as well! https://github.com/mapbox/node-cpp-skel/pull/115/files

**Comment by GretaCB** [comment]
Ah good call @millzpaugh , I didnt think to check older PRs. How about merging your PR after resolving the conflicts? Then @allieoop and I will make any other changes needed based on our perf work and the new mbxcli npm publish command.

**Comment by springmeyer** [comment]
Handled in #115 I think.

**Pull request closed without merging**
